version: "3.8"
services:
  authorizationServer:
    image: golang:1.22
    command: sh -c "go install github.com/air-verse/air && air"
    volumes:
      - ./authorizationServer/:/go/src/app
    working_dir: /go/src/app
    ports:
      - "8888:8888"
  client:
    image: golang:1.22
    command: sh -c "go install github.com/air-verse/air && air"
    volumes:
      - ./client/:/go/src/app
    working_dir: /go/src/app
    ports:
      - "9000:9000"
