version: "3.8"
services:
  authorization-server:
    build:
      dockerfile: docker/Dockerfile
    volumes:
      - ./authorizationServer/:/go/src/app
    working_dir: /go/src/app
    ports:
      - "9000:9000"
  client:
    build:
      dockerfile: docker/Dockerfile
    volumes:
      - ./client/:/go/src/app
    working_dir: /go/src/app
    ports:
      - "9001:9001"
  protected-resource:
    build:
      dockerfile: docker/Dockerfile
    volumes:
      - ./protectedResource/:/go/src/app
    working_dir: /go/src/app
    ports:
      - "9002:9002"
